APP_ENV: dev
SERVER_NAME: search-keyword-service
HTTP_HOST: 0.0.0.0
HTTP_PORT: 7003
SWAGGER_ENABLE: true

LOGGER_DEBUG: true
LOGGER_SENSITIVE: false

DB_CONNECTION:
DB_HOST:
DB_PORT:
DB_USERNAME:
DB_PASSWORD:
DB_NAME:
DB_SCHEMA:
DB_LOGSQL: true
DB_AUTOMIGRATE: false

REDIS_SINGLE: false
REDIS_ADDR:
REDIS_PASSWORD:

BASIC_AUTH_USER:
BASIC_AUTH_PASSWORD:

# Configurable schedule
CONFIG_TIME_SCHEDULE: 3600

SEARCH_ENGINE_ADDR: "google"
# SEARCH_ENGINE_ADDR: "bing"
# SEARCH_ENGINE_ADDR: "duckduckgo"