APP_ENV: dev
SERVER_NAME: search-keyword-service
HTTP_HOST: 0.0.0.0
HTTP_PORT: 7003
SWAGGER_ENABLE: true

LOGGER_DEBUG: true
LOGGER_SENSITIVE: false

JWT_SECRET: ""

DB_CONNECTION:
DB_HOST: localhost
DB_PORT: 5432
DB_USERNAME: postgres
DB_PASSWORD: password
DB_NAME: postgres
DB_SCHEMA: saving
DB_LOGSQL: true
DB_AUTOMIGRATE: false

GCP_SERVICE_ACCOUNT: ""
GCP_PROJECT_ID:

REDIS_CLUSTER: false
REDIS_ADDR: localhost:6379
REDIS_PASSWORD:

BASIC_AUTH_USER:
BASIC_AUTH_PASSWORD:
# Configurable schedule
CONFIG_TIME_SCHEDULE: 3600

SEARCH_ENGINE_ADDR: "google"
# SEARCH_ENGINE_ADDR: "bing"
# SEARCH_ENGINE_ADDR: "duckduckgo"